### ISSUE TITLE
Save before reading Outbreaks

### ISSUE THREAD

**Issue by lfmundim** [zyro670/PokeViewer.NET#12]
Howdy Zyro!

firstly: I saw that you managed to get hold of the memory pointers for Outbreaks, which I really was trying to learn how to get with Noexes and everything, so congrats to you!

second: i saw that it needs to save before reading outbreaks, else it will just read what i can only assume is trash data. Why is that? i tested removing the save before reading since it takes a while to save and its more moving parts... and it doesn't work. However with the save it looks like it does! again, why is that?

**Comment by zyro670** [comment]
We're reading from the save block not from real time pointers to know what the values are. Not sure if there are direct pointers to those in real time since a lot of the game is handled by lua. It does take a little bit to read through it all as I read through everything on each pass and just quit early if there aren't the max amount of outbreaks. I haven't been able to sit down yet and figure out how to do just do one big read at start then slice all the data apart accordingly.

**Comment by lfmundim** [comment]
That is actually very smart. Kudos!

I can take a peek into ways to optimize it, I saw it runs outbreak by outbreak, which is fine but takes some time. If I get somewhere ill push a PR :)

**Comment by zyro670** [comment]
Thank you! Much appreciated. I'll be messing around with it too after I finish some things on my other repos.

**Comment by lfmundim** [comment]
Its the least I can do after you did this huge work getting the pointers! I was very much looking forward to getting those, but is it a headache to mess with memory dumps

**Comment by zyro670** [comment]
Much appreciated, feel free to PR any convenience changes as you see would be helpful. I don’t have a background in coding so I am mostly trial and error for most things 😂
